spring.application.name=Sales-savvy_JwtAuth

spring.datasource.url=jdbc:mysql://localhost:3306/jwt_db
spring.datasource.username= YOUR_USERNAME
spring.datasource.password= YOUR_PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret= YOUR_JWT_SECRET
app.jwt.expiration-ms=3600000

# Razorpay Connection
razorpay.key-id= YOUR_KEY_ID
razorpay.key-secret= YOUR_KEY_SECRET
razorpay.currency=INR